version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
grpc:
    listen: 'tcp://127.0.0.1:9001'
    proto:
        - first.proto
        - second.proto
server:
    command: 'php app.php'
    relay: pipes
