version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
grpc:
    listen: 'tcp://127.0.0.1:9001'
    pool:
      debug: true
      num_workers: 3
    proto:
        - proto/user.proto
        - proto/category.proto
        - proto/product.proto
server:
    command: 'php app.php'
    relay: pipes
fileserver:
  address: 127.0.0.1:10101
  calculate_etag: true
  weak: false
  stream_request_body: true
  serve:
    - prefix: "/"
      root: "./public/uploads"
